= Spring GraphQL Documentation
Brian Clozel; Andreas Marek; Rossen Stoyanchev
:toc: left
:toclevels: 4
:tabsize: 4


[[web]]
== Web Transports

Spring GraphQL supports GraphQL requests over HTTP and over WebSocket. It comes with a choice
of handlers for Spring MVC and Spring WebFlux applications.



[[web-http]]
=== HTTP

`GraphQlHttpHandler` classes, in their respective WebMvc and WebFlux sub-packages, provide
handling of GraphQL over HTTP requests and both delegate to a common <<web-interceptor>>
chain for actual handling and query execution.

The HTTP handlers for WebMvc and WebFlux have equivalent functionality. Both perform
asynchronous execution of GraphQL queries, while the WebFlux handler also uses non-blocking
I/O to write to the HTTP response.

Requests should have the HTTP POST method with the query in the request body as defined in the
https://github.com/graphql/graphql-over-http/blob/main/spec/GraphQLOverHTTP.md[GraphQL over HTTP]
spec proposal.

The handlers can be exposed as endpoints by declaring a `RouterFunction` bean and using
the `RouterFunctions`, functional endpoint DSL for WebMvc or WebFlux respectively to
create the mappings. The Boot starter does this by default, see <<boot-graphql-web>> for
details or look in the `GraphQlWebMvcAutoConfiguration` or
`GraphQlWebFluxAutoConfiguration` classes for example config.



[[web-websocket]]
=== WebSocket

`GraphQlWebSocketHandler` classes, in their respective WebMvc and WebFlux sub-packages,
support GraphQL over WebSocket requests based on the
https://github.com/enisdenjo/graphql-ws/blob/master/PROTOCOL.md[protocol] defined in the
`graphql-ws` library that also lists a number of
https://github.com/enisdenjo/graphql-ws#recipes[recipes] for use with various clients.

[TIP]
.GraphQL Over WebSocket Protocols
====
There are two such protocols, one in the
https://github.com/apollographql/subscriptions-transport-ws[subscriptions-transport-ws]
library and another in the
https://github.com/enisdenjo/graphql-ws[graphql-ws] library. The former is not active and
succeeded by the latter. Read this
https://the-guild.dev/blog/graphql-over-websockets[blog post] for the history.
====

The WebSocket handlers for WebMvc and WebFlux have equivalent functionality. Both perform
asynchronous execution of GraphQL queries, but the WebFlux handler also uses non-blocking
I/O and back pressure to stream messages to the WebSocket connection.

GraphQL over WebSocket protocol supports the execution both queries and streaming
subscriptions and the <<web-interceptor>> can be used to intercept each query or
subscription request.

The handlers can be exposed as endpoints by declaring `SimpleUrlHandlerMapping` beans for
WebMvc or WebFlux respectively. The Boot starter provides options to enable and conifgure
all this, see<<boot-graphql-web>> for details or look in the `GraphQlWebMvcAutoConfiguration`
or `GraphQlWebFluxAutoConfiguration` classes for example configuration.



[[web-interceptor]]
=== `WebInterceptor` API

Web transport handlers for <<web-http>> and for <<web-websocket>> delegate to a
`WebGraphQlHandler` that represents a chain of `WebInterceptor` components, followed by a
`GraphQlSource` that actually invokes the GraphQL Java engine.

A `WebInterceptor` can be used to examine HTTP request input and potentially change the
`ExecutionInput` passed to `graphql.GraphQL`:

[source,java,indent=0,subs="verbatim,quotes"]
----
class MyInterceptor implements WebInterceptor {

	@Override
	public Mono<WebOutput> intercept(WebInput webInput, WebGraphQlHandler next) {
		webInput.configureExecutionInput((executionInput, builder) -> {
			Map<String, Object> map = ... ;
			return builder.extensions(map).build();
		});
		return next.handle(webInput);
	}
}
----

A `WebInterceptor` can be used to inspect and potentially modify the `ExecutionResult`
or add an HTTP response header:

[source,java,indent=0,subs="verbatim,quotes"]
----
class MyInterceptor implements WebInterceptor {

	@Override
	public Mono<WebOutput> intercept(WebInput webInput, WebGraphQlHandler next) {
		return next.handle(webInput)
				.map(webOutput -> {
					Object data = webOutput.getData();
					Object updatedData = ... ;
					return webOutput.transform(builder -> builder.data(updatedData));
				});
	}
}
----

`WebGraphQlHandler` provides a builder to assemble the processing chain given a
a set of `WebInterceptor` components and a `GraphQlSource`. This handler is then passed
to one of the web transport handlers. The Boot starter does all this by detecting beans
of type `WebInterceptor` and using them to build the processing chain, see
<<boot-graphql-web>> for details, or look in the `GraphQlWebMvcAutoConfiguration` or
`GraphQlWebFluxAutoConfiguration` classes for example configuration.



[[execution]]
==  Query Execution

TODO...


[[execution-configuring]]
=== Configuring the GraphQL Engine

TODO...


[[execution-datafetcher]]
=== `DataFetcher` Support

TODO...


[[execution-context]]
=== Context Management

TODO...


[[execution-exceptions]]
=== Exception Resolution

TODO...




[[data]]
== Data Integrations

TODO...


[[data-querydsl]]
=== QueryDsl

TODO...




[[data-security]]
== Security

TODO...




[[testing]]
== Testing

TODO...




[[boot-graphql]]
== Boot config

This project is tested against Spring Boot 2.4+.



[[boot-graphql-project]]
=== Project Setup

To create a project, go to https://start.spring.io and select starter(s) for the
GraphQL transports you want to use:

[cols="1,1,1"]
|===
| Starter | Transport | Implementation

| `spring-boot-starter-web`
| HTTP
| Spring MVC

| `spring-boot-starter-websocket`
| WebSocket
| WebSocket for Servlet apps

| `spring-boot-starter-webflux`
| HTTP, WebSocket
| Spring WebFlux

|===

In the generated project, add the starter `graphql-spring-boot-starter` manually:

[source,groovy,indent=0,subs="verbatim,quotes",role="primary"]
.Gradle
----
dependencies {
	// Spring GraphQL Boot starter
	implementation 'org.springframework.experimental:graphql-spring-boot-starter:1.0.0-SNAPSHOT'

	// ...
}

repositories {
	mavenCentral()
	maven { url 'https://repo.spring.io/milestone' }  // Spring milestones
	maven { url 'https://repo.spring.io/snapshot' }   // Spring snapshots
}
----
[source,xml,indent=0,subs="verbatim,quotes",role="secondary"]
.Maven
----
<dependencies>

	// Spring GraphQL Boot starter
	<dependency>
		<groupId>org.springframework.experimental</groupId>
		<artifactId>graphql-spring-boot-starter</artifactId>
		<version>1.0.0-SNAPSHOT</version>
	</dependency>

	<!-- ... -->

</dependencies>

<!-- For Spring project milestones or snapshot releases -->
<repositories>
	<repository>
		<id>spring-milestones</id>
		<name>Spring Milestones</name>
		<url>https://repo.spring.io/milestone</url>
	</repository>
	<repository>
		<id>spring-snapshots</id>
		<name>Spring Snapshots</name>
		<url>https://repo.spring.io/snapshot</url>
		<snapshots>
			<enabled>true</enabled>
		</snapshots>
	</repository>
</repositories>
----

[NOTE]
.GraphQL Spring Boot Starter Group Id
====
The starter is scheduled to move from the Spring GraphQL repository to the Spring Boot
repository, after Spring Boot 2.6 is released. The starter group id will then change
from `org.springframework.experimental` to `org.springframework.boot` and will be
released in Spring Boot 2.7 building on Spring GraphQL 1.0.
====



[[boot-graphql-schema]]
=== GraphQL Schema

By default, GraphQL schema files are expected to be in `src/main/resources/graphql` and have
the extension ".graphqls", ".graphql", ".gql", or ".gqls". You can customize the
schema locations to check as follows:

[source,properties,indent=0,subs="verbatim,quotes"]
----
spring.graphql.schema.locations=classpath:graphql/
----

The GraphQL schema can be viewed over HTTP at "/graphql/schema". This is not enabled by
default:

[source,properties,indent=0,subs="verbatim,quotes"]
----
spring.graphql.schema.printer.enabled=false
----


[[boot-graphql-datafetcher]]
=== `DataFetcher` Registration

You can declare `RuntimeWiringCustomizer` beans in your Spring config and use those to
register data fetchers, type resolvers, and more with the GraphQL engine:

[source,java,indent=0,subs="verbatim,quotes"]
----
@Component
public class PersonDataWiring implements RuntimeWiringCustomizer {

	private final PersonService service;

	public PersonDataWiring(PersonService service) {
		this.service = service;
	}

	@Override
	public void customize(RuntimeWiring.Builder builder) {
		builder.type("Query", wiring ->
				wiring.dataFetcher("people", env -> this.service.findAll()));
	}
}
----


[[boot-graphql-web]]
=== Web Transports

The GraphQL HTTP endpoint is at HTTP POST "/graphql" by default. The path can be customized:

[source,properties,indent=0,subs="verbatim,quotes"]
----
spring.graphql.path=/graphql
----

The GraphQL WebSocket endpoint supports WebSocket handshakes at "/graphql" by default.
The below shows the properties that apply for WebSocket handling:

[source,properties,indent=0,subs="verbatim,quotes"]
----
spring.graphql.websocket.path=/graphql

# Time within which a "CONNECTION_INIT" message must be received from the client
spring.graphql.websocket.connection-init-timeout=60s
----

The GraphQL WebSocket endpoint is not enabled by default. To enable it:

- For a Servlet application, add the WebSocket starter `spring-boot-starter-websocket`.
- For a WebFlux application, set the `spring.graphql.websocket.path` application property.

`WebInterceptor` beans declared in Spring configuration are detected and registered to
intercept for both GraphQL requests over HTTP and over WebSocket.


[[boot-graphql-graphiql]]
=== GraphiQL Page

The Spring Boot starter includes a https://github.com/graphql/graphiql[GraphiQL] page
that is exposed at "/graphiql" by default. You can configure that as follows:

[source,properties,indent=0,subs="verbatim,quotes"]
----
spring.graphql.graphiql.enabled=true
spring.graphql.graphiql.path=/graphiql
----




[[boot-graphql-metrics]]
=== Metrics

When the starter `spring-boot-starter-actuator` is present on the classpath, metrics for
GraphQL requests are collected. You can disable metrics collection as follows:

[source,properties,indent=0,subs="verbatim,quotes"]
----
management.metrics.graphql.autotime.enabled=false
----

Metrics can be exposed with an Actuator web endpoint.
The following sections assume that its exposure is enabled in your application configuration, as follows:

[source,properties,indent=0,subs="verbatim,quotes"]
----
management.endpoints.web.exposure.include=health,metrics,info
----


[[boot-graphql-metrics-request-timer]]
==== GraphQL Request Timer

A Request metric timer is available at `/actuator/metrics/graphql.request`.

[cols="1,2,2"]
|===
|Tag | Description| Sample values

|outcome
|Request outcome
|"SUCCESS", "ERROR"
|===


[[boot-graphql-metrics-datafetcher-timer]]
==== GraphQL `DataFetcher` Timer

A `DataFetcher` metric timer is available at `/actuator/metrics/graphql.datafetcher`.

[cols="1,2,2"]
|===
|Tag | Description| Sample values

|path
|data fetcher path
|"Query.project"

|outcome
|data fetching outcome
|"SUCCESS", "ERROR"
|===


[[boot-graphql-metrics-error-counter]]
==== GraphQL Error Counter

A GraphQL error metric counter is available at `/actuator/metrics/graphql.error`.

[cols="1,2,2"]
|===
|Tag | Description| Sample values

|errorType
|error type
|"DataFetchingException"

|errorPath
|error JSON Path
|"$.project"
|===



[[boot-graphql-testing]]
=== Testing

When the starter `spring-boot-starter-test` is present on the classpath, a `WebGraphQlTester`
is configured and available for injection into tests.

For GraphQL over HTTP with Spring MVC, using `MockMvc` as the server:

[source,java,indent=0,subs="verbatim,quotes"]
----
@SpringBootTest
@AutoConfigureMockMvc
@AutoConfigureGraphQlTester
public class MockMvcGraphQlTests {

	@Autowired
	private WebGraphQlTester graphQlTester;

}
----

For GraphQL over HTTP with Spring WebFlux, using a
https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.testing.spring-boot-applications.with-mock-environment[mock server]:

[source,java,indent=0,subs="verbatim,quotes"]
----
@SpringBootTest
@AutoConfigureWebTestClient
@AutoConfigureGraphQlTester
public class MockMvcGraphQlTests {

	@Autowired
	private WebGraphQlTester graphQlTester;

}
----

For GraphQL over HTTP with a
https://docs.spring.io/spring-boot/docs/current/reference/html/features.html#features.testing.spring-boot-applications.with-running-server[running server]:

[source,java,indent=0,subs="verbatim,quotes"]
----
@SpringBootTest(webEnvironment = SpringBootTest.WebEnvironment.RANDOM_PORT)
@AutoConfigureGraphQlTester
public class MockMvcGraphQlTests {

	@Autowired
	private WebGraphQlTester graphQlTester;

}
----

Subscriptions can be tested without a WebSocket layer as shown below:

[source,java,indent=0,subs="verbatim,quotes"]
----
@SpringBootTest
@AutoConfigureGraphQlTester
public class MockMvcGraphQlTests {

	@Autowired
	private WebGraphQlTester graphQlTester;

	@Test
	void subscription() {
		Flux<String> result = this.graphQlTester.query("subscription { greetings }")
				.executeSubscription()
				.toFlux("greetings", String.class);

		// Use StepVerifier from "reactor-test" to verify the stream...
		StepVerifier.create(result)
				.expectNext("Hi")
				.expectNext("Bonjour")
				.expectNext("Hola")
				.verifyComplete();
	}

}
----

The above subscription test is performed directly against the `WebGraphQlHandler` that
both HTTP and WebSocket transports delegate to. It passes through the `WebInterceptor`
chain and then calls GraphQL Java which returns a Reactive Streams `Publisher`.




[[samples]]
== Samples

This Spring GraphQL repository contains
https://github.com/spring-projects/spring-graphql/tree/main/samples[sample applications] for various scenarios.

You can run those by cloning this repository and running main application classes from
your IDE or by typing the following on the command line:

[source,bash,indent=0,subs="verbatim,quotes"]
----
$ ./gradlew :samples:{sample-directory-name}:bootRun
----
