github-repo: "https://github.com/spring-projects/spring-graphql.git"
github-repo-name: "spring-projects/spring-graphql"
docker-hub-organization: "springci"
artifactory-server: "https://repo.spring.io"
branch: "main"
milestone: "1.1.x"
build-name: "spring-graphql"
pipeline-name: "spring-graphql"
concourse-url: "https://ci.spring.io"
task-timeout: 45m
registry-mirror-host: docker.repo.spring.io
registry-mirror-username: ((artifactory-username))
registry-mirror-password: ((artifactory-password))
sonatype-staging-profile: "org.springframework"